{{- if and (eq (.Values.secrets).provider "external-secrets") ((.Values.secrets).externalSecrets).enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "aeterna.fullname" . }}
  labels:
    {{- include "aeterna.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.secrets.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    {{- toYaml .Values.secrets.externalSecrets.secretStoreRef | nindent 4 }}
  target:
    name: {{ include "aeterna.fullname" . }}-external
    creationPolicy: Owner
  data:
    {{- with .Values.secrets.externalSecrets.remoteRefs }}
    {{- if .postgresqlPassword }}
    - secretKey: postgresql-password
      remoteRef:
        key: {{ .postgresqlPassword }}
    {{- end }}
    {{- if .redisPassword }}
    - secretKey: redis-password
      remoteRef:
        key: {{ .redisPassword }}
    {{- end }}
    {{- if .opalMasterToken }}
    - secretKey: opal-master-token
      remoteRef:
        key: {{ .opalMasterToken }}
    {{- end }}
    {{- if .llmApiKey }}
    - secretKey: llm-api-key
      remoteRef:
        key: {{ .llmApiKey }}
    {{- end }}
    {{- end }}
{{- end }}
