{{- if and .Values.aeterna.enabled .Values.aeterna.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aeterna.serviceAccountName" . }}
  labels:
    {{- include "aeterna.labels" . | nindent 4 }}
  {{- with .Values.aeterna.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.aeterna.serviceAccount.automount }}
{{- end }}
